version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/backend" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "yarn" # See documentation for possible values
    directory: "/frontend" # Location of package manifests
    schedule:
      interval: "daily"